Revert "Revert "Improve the password strength check""
secretkeylabs/xverse-web-extension pull request #430
Opened 2023-05-18 16:22 UTC by dhriaznov

Reverts secretkeylabs/xverse-web-extension#429

2023-05-23 07:03 UTC, DuskaT021 requested changes
left comments in the task ticket

2023-05-25 18:18 UTC, dhriaznov commented
I updated this PR, @DuskaT021, could you please test it again?

2023-05-29 16:09 UTC, DuskaT021 commented
tested  and it can be merged 👍

2023-05-29 16:09 UTC, DuskaT021 approved these changes

2023-05-29 16:09 UTC, merged