[ENG-2961] Fix eslint errors for web extension
secretkeylabs/xverse-web-extension pull request #617
Opened 2023-10-12 13:52 UTC by dhriaznov

# 🔘 PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Enhancement
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

# 📜 Background
Provide a brief explanation of why this pull request is needed. Include the problem you are solving or the functionality you are adding. Reference any related issues.

Issue Link: #[issue_number]
Context Link (if applicable):

# 🔄 Changes
Enumerate the changes made in this pull request, detailing what has been modified, added, or removed. Include technical details and implications if necessary.

Impact:
- Explain the broader impact of these changes.
- How it improves performance, fixes bugs, adds functionality, etc.

# 🖼 Screenshot / 📹 Video
Include screenshots or a video demonstrating the changes. This is especially helpful for UI changes.

# ✅ Review checklist
Please ensure the following are true before merging:

- [ ] Code Style is consistent with the project guidelines.
- [ ] Code is readable and well-commented.
- [ ] No unnecessary or debugging code has been added.
- [ ] Security considerations have been taken into account.
- [ ] The change has been manually tested and works as expected.
- [ ] Breaking changes and their impacts have been considered and documented.
- [ ] Code does not introduce new technical debt or issues.

2023-10-19 10:57 UTC, victorkirov commented on src/app/hooks/queries/useAppConfig.ts
>        }
```suggestion
      const response = await getAppConfig();
      if (response.data.btcApiURL && network.type === 'Mainnet' && !btcApiUrl) {
        const updatedNetwork = { ...network, btcApiUrl: response.data.btcApiURL };
        dispatch(ChangeNetworkAction(updatedNetwork, networkAddress, ''));
      }
      return response;

```

2023-10-19 11:01 UTC, victorkirov requested changes
This is awesome 🎉  Just left 2 comments for cleanup 🙏

2023-10-19 11:32 UTC, dhriaznov commented
Thanks @victorkirov, I updated the PR, could you take a second look, please?

2023-10-19 12:39 UTC, victorkirov approved these changes
LGTM 🚀 🚢

2023-10-20 01:18 UTC, blehitsahmad commented
@dhriaznov good to merge -- [comment](https://linear.app/xverseapp/issue/ENG-2961/fix-eslint-errors-for-web-extension#comment-a755e2a3) added to the linear ticket.

2023-10-24 08:05 UTC, merged